version: '3.8'
services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=matencio
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678/webhook/calculate
      - GENERIC_TIMEZONE=Atlantic/Canary
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`matencio`)"

  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - n8n
